// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// costanza
Rcpp::DataFrame costanza(const Rcpp::NumericMatrix& data, const Rcpp::NumericMatrix& reference, const Rcpp::NumericVector resolution);
RcppExport SEXP _mrgf_costanza(SEXP dataSEXP, SEXP referenceSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(costanza(data, reference, resolution));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mrgf_costanza", (DL_FUNC) &_mrgf_costanza, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mrgf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
