# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Multi-resolution Goodness-of-Fit
#' @name costanza
#' @author Rolf Simoes, \email{rolf.simoes@@inpe.br}
#'
#' @description Compute multi-resolution Goodness-of-Fit on two matrices
#' with equal dimensions.
#' @references Costanza_Paper_Reference
#'
#' @param data         matrix of data.
#' @param reference    matrix of data to be compared (must have the same size as `x`).
#' @param resolution   desired number of clusters
#' @return data frame with all multireolution parameters and metrics.
#'
#' @examples
#' require(raster)
#' require(ggplot2)
#' # Costanza with 10x10 images
#' f1 <- system.file("extdata/tif/costanza1.tif", package = "mrgf")
#' f2 <- system.file("extdata/tif/costanza2.tif", package = "mrgf")
#' # open files        
#' r1 <- raster::raster(f1)
#' r2 <- raster::raster(f2)
#' # plot images
#' plot(r1)
#' plot(r2)
#' # load data into matrices
#' m1 <- matrix(r1, nrow = nrow(r1))
#' m2 <- matrix(r2, nrow = nrow(r2))
#' # perform multi-resolution goodness-of-fit        
#' result <- costanza(m1, m2, resolution = 1:10)
#' # plot the result
#' ggplot(result) + 
#'     geom_line(aes(resolution, 
#'                   class_acc, 
#'                   colour = as.factor(classes), 
#'                   group = classes)) +
#'     geom_line(aes(resolution, global_acc))
#'
#' @export
costanza <- function(data, reference, resolution) {
    .Call(`_mrgf_costanza`, data, reference, resolution)
}

