# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

win <- function(x, i, j, i_len, j_len) {
    .Call(`_mrgf_win`, x, i, j, i_len, j_len)
}

slide <- function(x, i_len, j_len) {
    invisible(.Call(`_mrgf_slide`, x, i_len, j_len))
}

costanza <- function(x, y, resolution) {
    .Call(`_mrgf_costanza`, x, y, resolution)
}

